-- =========================================================================
-- BUSINESS INTELLIGENCE ANALYSIS EXAMPLES
-- Based on data generated by the Retail Pipeline
-- Author: Willian Phaiffer Cardoso
-- =========================================================================

-- 1. REVENUE ANALYSIS BY COUNTRY (Geographic Performance)
-- Goal: Identify which countries generate the most revenue to focus marketing efforts.
-- Source: GOLD Layer
SELECT
    country AS Country,
    FORMAT(SUM(revenue), 2) AS Total_Revenue,
    COUNT(DISTINCT category) AS Categories_Sold
FROM gold_retail.category_performance
GROUP BY country
ORDER BY SUM(revenue) DESC;

-- 2. PAYMENT PREFERENCE (Financial)
-- Goal: Understand which payment methods are most used to negotiate processing rates.
-- Source: SILVER Layer
SELECT
    payment_type AS Payment_Method,
    COUNT(transaction_id) AS Transaction_Count,
    FORMAT(SUM(total_amount), 2) AS Sales_Volume,
    FORMAT(AVG(total_amount), 2) AS Average_Ticket
FROM silver_retail.sales_clean
GROUP BY payment_type
ORDER BY Sales_Volume DESC;

-- 3. SALES SEASONALITY (Temporal Trend)
-- Goal: View daily sales evolution for inventory planning.
-- Source: SILVER Layer
SELECT
    transaction_date AS Date,
    COUNT(transaction_id) AS Sales_Count,
    FORMAT(SUM(total_amount), 2) AS Daily_Revenue
FROM silver_retail.sales_clean
GROUP BY transaction_date
ORDER BY transaction_date DESC
LIMIT 10;

-- 4. TOP 5 BEST-SELLING PRODUCTS (Product)
-- Goal: Identify "Best Sellers" to maintain inventory levels.
-- Source: SILVER Layer
SELECT
    category AS Category,
    product_id,
    SUM(quantity) AS Units_Sold,
    FORMAT(SUM(total_amount), 2) AS Revenue_Generated
FROM silver_retail.sales_clean
GROUP BY category, product_id
ORDER BY Units_Sold DESC
LIMIT 5;

-- 5. VIP CUSTOMERS (CRM)
-- Goal: Identify highest-spending customers for loyalty programs.
-- Source: SILVER Layer
SELECT
    customer_email,
    COUNT(transaction_id) AS Purchase_Frequency,
    FORMAT(SUM(total_amount), 2) AS Total_Spent
FROM silver_retail.sales_clean
GROUP BY customer_email
ORDER BY SUM(total_amount) DESC
LIMIT 10;